config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'
  resources :orders do
    collection do
      get 'summary'
      post 'confirm'
    end
  end
  get '/admin_account/:id', to: "admin_accounts#index", as: "admin_account"
  get '/dashboard', to: "dashboard#index"
  # Defines the root path route ("/")
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }, skip: [ :passwords, :confirmations, :unlocks, :omniauth_callbacks]

  get '*others', to: "homepage#index"

  root "homepage#index"
end

app/views/shared/_header.html.erb
<div class="flex bg-blue md:bg-white text-white md:text-grey-dark">
  <div class="md:hidden h-[50px] p-4 flex items-center" id="side-nav-icon">
    <i class="bi-list"></i>
  </div>
  <div class="h-[50px] w-[100%] flex items-center font-bold p-4">
    <% if current_page?(dashboard_path) %>
      Dashboard
    <% elsif controller_name=='orders' %>
      Orders
    <% elsif current_namespace?('users') %>
      Account Details
    <% end %>
  </div>
</div>


<script>
  function showSideNav() {
    const sideNav = document.getElementById('side-nav');
    sideNav.classList.toggle('hidden');
  }

  document.addEventListener("turbo:load", function() {
    const sideNavIcon = document.getElementById('side-nav-icon');

    sideNavIcon.addEventListener("click", showSideNav);
  })
</script>

app/views/shared/_side_nav.html.erb
<div class="hidden md:flex bg-white fixed w-[80%] md:w-[20%] h-screen flex flex-col justify-between p-4 border-r-2 border-grey-light border-solid" id="side-nav">
  <div class="flex flex-col gap-y-3.5">
    <div class="flex justify-between">
      <div class="flex items-center mb-4 gap-x-2.5">
        <%= image_tag 'logo_blue.svg', alt: 'logo', class: 'w-[40px]' %>
        <p class="font-bold text-sm">Cedis2RMB</p>
      </div>
      <div class="md:hidden" id="close-side-nav">
        <i class="bi-x-square text-2xl text-blue-dark"></i>
      </div>
    </div>
    <div class="flex flex-col gap-y-1">
      <div class= "<%='active-link' if current_page?(dashboard_path) %> w-[100%] h-[30px] px-2 flex items-center m-auto rounded">
        <%= link_to "Dashboard", dashboard_path %>
      </div>
      <div class= "<%='active-link' if current_page?(root_path) %> w-[100%] h-[30px] px-2 flex items-center m-auto rounded">
        <%= link_to "Buy RMB", new_order_path, target: "_blank" %>
      </div>
      <div class= "<%='active-link' if controller_name=='orders' %> w-[100%] h-[30px] px-2 flex items-center m-auto rounded">
        <%= link_to "My Orders", orders_path %>
      </div>
      <div class= "<%='active-link' if current_namespace?('users') %> w-[100%] h-[30px] px-2 flex items-center m-auto rounded">
        <%= link_to "Edit Account", edit_user_registration_path %>
      </div>
    </div>
  </div>
  <div>
    <%= 
      button_to 'Logout',
      destroy_user_session_path,
      method: :delete,
      class: "bg-blue w-[100%] m-auto rounded text-white h-[30px]"
    %>
  </div>
</div>

<script>
  function hideSideNav() {
    const sideNav = document.getElementById('side-nav');
    sideNav.classList.add('hidden');
  }

  document.addEventListener("turbo:load", function() {
    const closeSideNav = document.getElementById('close-side-nav');
    const sideNavLinks = document.querySelectorAll('#side-nav a');

    closeSideNav.addEventListener("click", hideSideNav);

    sideNavLinks.forEach(link => {
      link.addEventListener('click', hideSideNav);
    });
  })
</script>