config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'
  resources :orders do
    collection do
      get 'summary'
      post 'confirm'
    end
  end
  get '/admin_account/:id', to: "admin_accounts#index", as: "admin_account"
  get '/dashboard', to: "dashboard#index"
  # Defines the root path route ("/")
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }, skip: [ :passwords, :confirmations, :unlocks, :omniauth_callbacks]

  get '*others', to: "homepage#index"

  root "homepage#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :recipient_account
  belongs_to :payer_account

  accepts_nested_attributes_for :payer_account
  accepts_nested_attributes_for :recipient_account

  before_create :set_order_code

  STATUS = [['Pending', 'Pending'], ['Cancel', 'Cancelled']]

  def self.status_options
    STATUS
  end

  private

  def set_order_code
    loop do
      self.order_code = format('%06d', rand(0..999999))
      break unless Order.exists?(order_code: order_code)
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update ]
  before_action :authenticate_user!, only: %i[index update edit show]

  rescue_from ActiveRecord::RecordNotFound, with: :order_not_found

  # GET /orders or /orders.json
  def index
    @page = params[:page].to_i.positive? ? params[:page].to_i : 1
    @orders_status = params[:orders_status]
    @orders = Order.where(user: current_user).order(created_at: :desc).paginate(page: params[:page], per_page: 25)

    # Filters
    @orders = Order.where(user: current_user, status: params[:orders_status]).paginate(page: params[:page], per_page: 25).order(created_at: :desc) if params[:orders_status].present?
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    order_params = session[:order_params]
    if order_params.present?
      @order = Order.new(order_params)
      @payer_account = @order.build_payer_account(order_params["payer_account_attributes"])
      @recipient_account = @order.build_recipient_account(order_params["recipient_account_attributes"])
    else
      @order = Order.new
      @payer_account = @order.build_payer_account
      @recipient_account = @order.build_recipient_account
    end

    @exchange_rate = ExchangeRate.current_rate.value
    @recipient_account_types = AccountType.rmb_accounts
    @payer_account_types = AccountType.cedi_accounts
    @limit = Limit.order(created_at: :desc).first
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    uploaded_image = order_params["recipient_account_attributes"]["qr_code"]
    bucket = FIREBASE_STORAGE.bucket(BUCKET_NAME)

    # Get file extension
    original_filename = uploaded_image.original_filename
    file_extension = File.extname(original_filename)

    # Give file random uuid name and extension
    temp_image_name = "#{SecureRandom.uuid}#{file_extension}"
    file = bucket.create_file(uploaded_image.tempfile, temp_image_name)

    params_hash = order_params.to_h

    # Build qr_link
    image_url = "https://firebasestorage.googleapis.com/v0/b/#{bucket.name}/o/#{CGI.escape(temp_image_name)}?alt=media"
    params_hash['recipient_account_attributes']['qr_code_url'] = image_url

    # Remove qr_code from recipient_account_attributes
    params_hash['recipient_account_attributes'].delete('qr_code')

    # Convert hash back to ActionController::Parameters and store in session
    session[:order_params] = ActionController::Parameters.new(params_hash)

    redirect_to summary_orders_path
  end

  # GET /orders/summary
  def summary
    order_params = session[:order_params]
    @recipient_account = RecipientAccount.new(order_params[:recipient_account_attributes])
    @payer_account = PayerAccount.new(order_params[:payer_account_attributes])
    @order = Order.new(order_params)
    @exchange_rate = ExchangeRate.current_rate.value
  end

  # POST /orders/confirm
  def confirm
    order_params = session[:order_params]
    @order = Order.new(order_params)
    @recipient_account = RecipientAccount.new(order_params["recipient_account_attributes"])
    @payer_account = PayerAccount.new(order_params["payer_account_attributes"])

    set_order_properties

    respond_to do |format|
      if @order.save
        session.delete(:order_params)
        format.html { redirect_to "/admin_account/#{@order.id}", notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(
        :amount, :user_id, :rate, :status, :whatsapp_number, :reference,
        payer_account_attributes: [:account_number, :account_name, :account_type_id],
        recipient_account_attributes: [:account_number, :account_name, :account_type_id, :qr_code]
      )
    end

    def set_order_properties
      @order.rate = ExchangeRate.current_rate.value
      @order.status = "Pending"
      @order.recipient_account = @recipient_account
      @order.payer_account = @payer_account
      @order.user = current_user if current_user
    end

    def order_not_found
      render 'homepage/index', status: 404
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def order_status_bg(status)
    case status
    when 'Pending'
      "bg-yellow-light"
    when 'Completed'
      "bg-green-light"
    when 'Cancelled'
      "bg-red-light"
    end
  end

  def order_status_bg_dark(status)
    case status
    when 'Pending'
      "bg-yellow"
    when 'Completed'
      "bg-green"
    when 'Cancelled'
      "bg-red"
    end
  end

  def order_status_color(status)
    case status
    when 'Pending'
      "text-yellow"
    when 'Completed'
      "text-green"
    when 'Cancelled'
      "text-red"
    end
  end
end

app/views/orders/_form.html.erb
<%= form_with(model: order, class: "contents") do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rate %>
    <%= form.text_field :rate, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.text_field :status, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/orders/_header.html.erb
<% if current_page?(orders_path) %>
  <div class="flex gap-x-4 py-4 px-8 rounded-t-lg border-b-2 border-solid border-grey-light bg-white">
    <%= link_to "All",
      orders_path(orders_status: nil, page: 1),
      class: "#{'active-tab' if current_page?(orders_path(orders_status: nil, page: params[:page]))} py-1 px-4 text-black"
    %>
    <%= link_to "Pending",
      orders_path(orders_status: "Pending", page: 1),
      class: "#{'active-tab' if current_page?(orders_path(orders_status: "Pending", page: params[:page]))} py-1 px-4 text-black"
    %>
    <%= link_to "Completed",
      orders_path(orders_status: "Completed", page: 1),
      class: "#{'active-tab' if current_page?(orders_path(orders_status: "Completed", page: params[:page]))} py-1 px-4 text-black"
    %>
  </div>
<% elsif current_page?(order_path) %>
  <div class="flex gap-x-4 py-4 px-8 rounded-lg border-b-2 border-solid border-grey-light bg-white">
    <div>
      <%= link_to orders_path(orders_status: params[:orders_status], page: params[:page]),
        class: "px-4 py-2 bg-blue bg-opacity-10 rounded text-blue font-bold" do
      %>
        <i class="bi-arrow-left text-2xl"></i>
      <% end %>
    </div>
    <div>Back to orders</div>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= order.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Amount:</strong>
    <%= order.amount %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Rate:</strong>
    <%= order.rate %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= order.status %>
  </p>

</div>

app/views/orders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing order</h1>

  <%= render "form", order: @order %>

  <%= link_to "Show this order", @order, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to orders", orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/orders/index.html.erb
<div class="w-full p-2 bg-blue-light">
  <%= render 'header' %>

  <div class="bg-white rounded-b-lg">
    <div class="p-4 overflow-x-scroll">
      <table class="md:text-sm min-w-[800px] md:min-w-[80%] w-[100%]">
        <thead>
          <tr class="text-left bg-grey-light bg-opacity-50 border-b-2 border-t border-grey-light">
            <th class="p-2">S/N</th>
            <th class="p-2">Order Code</th>
            <th class="p-2">Amount(GHS)</th>
            <th class="p-2">Rate</th>
            <th class="p-2">Status</th>
            <th class="p-2">Date</th>
            <th class="p-2">Action</th>
          </tr>
        </thead>
        <tbody class="bg-white">
          <% @orders.each_with_index do |order, index| %>
            <tr class="bg-white border-b border-grey-light border-solid py-0">
              <!-- Calculation to get the index -->
              <td class="p-2"><%= (index+(@page*25)-24) %></td>
              <td class="p-2"><%= order.order_code %></td>
              <td class="p-2"><%= format_amount(order.amount) %></td>
              <td class="p-2"><%= format_amount(order.rate) %></td>
              <td class="p-2">
                <div class="rounded text-center py-0.5 <%= order_status_bg(order.status) %>"><%= order.status %></div>
              </td>
              <td class="p-2"><%= format_date(order.created_at)%></td>
              <td class="p-2">
                <%= link_to "View Details", order, class: "bg-blue rounded p-1 text-white" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="custom-pagination mt-4">
        <%= will_paginate @orders,
          inner_window: 2,
          outer_window: 0
        %>
      </div>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<div class="bg-blue-light p-2 min-h-screen">
<!-- <div class="bg-blue-light p-6  flex justify-center items-center"> -->
  <div class="lg:w-[70%] max-w-4xl mx-auto my-4 p-4 rounded-xl bg-white shadow-lg">
    <!-- Header Section -->
    <div class="flex items-center gap-x-6 mb-6">
      <div class=" bg-white px-2 text-bold rounded-lg w-fit h-fit border-4 border-grey-light hover:shadow-md transition-shadow">
        <%= link_to root_path do %>
          <i class="bi-arrow-left text-2xl"></i>
        <% end %>
      </div>
      <h1 class="font-bold text-3xl text-blue-dark">New order</h1>
    </div>

    <hr class="mb-2 md:mb-8 border-grey-dark">

    <%#= link_to "Back to orders", orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

    <div class="space-y-8 text-grey-dark">
      <%= form_with(model: @order, class: "contents", id: "currencyform") do |form| %>
        <div class="md:flex md:justify-between md:flex-row-reverse mb-8">
          
          <!--Display rate -->
          <div class="flex items-center justify-between md:justify-center space-x-2 my-2">
            <span class="font-semibold">Rate:</span>
            <p class="text-xl text-blue-dark font-bold bg-grey-light bg-opacity-30 text-center py-1 px-3 rounded-lg border border-grey-light">
              <%= @exchange_rate %>
            </p>
          </div>

          <!-- Currency conversion -->
          <div>
            <h3 class="block text-base font-semibold">Select Currency</h3>
            <div class="flex gap-x-8">
              <label class="flex items-center space-x-1">
                <%= radio_button_tag :currency, "cedi", true, class:"mr-2" %>
                Cedis ₵
              </label>
              <label class="flex items-center space-x-1">
                <%= radio_button_tag :currency, "rmb", false, class:"mr-2" %>
                RMB ¥
              </label>
            </div>
          </div>
        </div>

        <div class="gap-x-4 items-end justify-between space-y-2">
          <div class="flex-1">
            <label class="block text-base font-semibold">Enter Amount</label>
            <%= form.number_field :temp_amount, id: "temp_amount", value: @order.amount, placeholder: "e.g. 100", required: true, 
              class: "w-full rounded-md border border-grey-light outline-none px-3 py-2 mt-2 h-[40px] placeholder:font-light placeholder:italic",
              name: nil, step: ".01", min: @limit.min_value, max: @limit.max_value %>
          </div>

          <diV class="flex items-end gap-x-2">
            <button type="button" id="convert-btn"
              class="bg-blue-light text-blue-dark px-4 font-medium border border-blue-light rounded-md h-[40px]">
              Convert to RMB
            </button>

            <!-- Display the Conversion Result -->
            <div class="flex items-center text-center py-1 px-3 h-[40px] bg-grey-light bg-opacity-30 rounded-md border border-grey-light">
              <p id="result" class="font-semibold font-lg text-grey-dark">0.00</p>
            </div>
          </div>
        </div>

        <div>
          <%= form.hidden_field :amount, id: "amount", class: "hidden" %>
        </div>

        <hr class="text-grey-dark my-8"/>

        <!-- Recipient account -->
        <%= form.fields_for :recipient_account do |recipient_form| %>
          <div>
            <h1 class="text-blue-dark text-3xl font-bold">Account details</h1>
            <div class="text-sm text-grey-dark">(The account you want us to credit. Upload the QR code or else enter the account details. You don't have to do both.)</div>
            <hr class="text-grey-light mb-8"/>

            <!-- Account code-->
            <div>
              <label class="block text-base font-semibold">Upload account QR code</label>
              <%= recipient_form.file_field :qr_code, accept: "image/jpeg, image/jpg, image/png" %>
            </div>

            <!-- Alternative -->
            <div class="text-2xl font-semibold text-blue-dark my-4"> OR </div>

            <!-- Account type, name & number-->
            <div class="flex-1 mb-6">
              <label class="block text-base font-semibold">Account Type</label>
              <%= recipient_form.select :account_type_id,
                options_from_collection_for_select(@recipient_account_types || [], :id, :name, @recipient_account[:account_type_id]),
                {},
                {class: "w-full md:w-[50%] block rounded-md border border-grey-light outline-none"}
              %>
            </div>
            <div class="flex-1 mb-6">
              <label class="block text-base font-semibold">Account Name</label>
              <%= recipient_form.text_field :account_name, value: @recipient_account.account_name, placeholder: "e.g. Jane Doe", 
                class: "w-full md:w-[50%] rounded-md border border-grey-light outline-none px-3 py-2 mt-2 h-[40px] placeholder:font-light placeholder:italic" %>
            </div>
            <div class="flex-1">
              <label class="block text-base font-semibold">Account Number</label>
              <%= recipient_form.text_field :account_number, value: @recipient_account.account_number, placeholder: "e.g. 0011223344556677", 
                class: "w-full md:w-[50%] rounded-md border border-grey-light outline-none px-3 py-2 mt-2 h-[40px] placeholder:font-light placeholder:italic" %>
            </div>
          </div>
        <% end %>

        <hr class="text-grey-dark my-8"/>

        <!-- Payer's account -->
        <%= form.fields_for :payer_account do |payer_form| %>
          <div>
            <h1 class="text-blue-dark text-3xl font-bold">Payment details</h1>
            <div class="text-sm text-grey-dark">(The account you would be making payment from.)</div>
            <hr class="text-grey-light mb-8"/>

            <!-- Account name & number-->
            <div class="flex-1 mb-6">
              <label class="block text-base font-semibold">Account Type</label>
              <%= payer_form.select :account_type_id,
                options_from_collection_for_select(@payer_account_types || [], :id, :name, @payer_account[:account_type_id]),
                {},
                {class: "w-full md:w-[50%] block rounded-md border border-grey-light outline-none"}
              %>
            </div>
            <div class="flex-1 mb-6">
              <label class="block text-base font-semibold">Account Name</label>
              <%= payer_form.text_field :account_name, value: @payer_account.account_name, placeholder: "e.g. John Doe", 
                class: "w-full md:w-[50%] rounded-md border border-grey-light outline-none px-3 py-2 mt-2 h-[40px] placeholder:font-light placeholder:italic" %>
            </div>
            <div class="flex-1">
              <label class="block text-base font-semibold">Account Number</label>
              <%= payer_form.text_field :account_number, value: @payer_account.account_number, placeholder: "e.g. 0011223344556677", 
                class: "w-full md:w-[50%] rounded-md border border-grey-light outline-none px-3 py-2 mt-2 h-[40px] placeholder:font-light placeholder:italic" %>
            </div>
          </div>
        <% end %>

        <hr class="text-grey-dark my-8"/>

        <!-- Contact info -->
        <div>
          <h1 class="text-blue-dark text-3xl font-bold">Contact Info</h1>
          <div class="text-sm text-grey-dark">(Enter number for receipt confirmation.)</div>
          <hr class="text-grey-light mb-8"/>

          <div class="flex-1">
            <label class="block text-base font-semibold">WhatsApp Number</label>
            <%= form.text_field :whatsapp_number, value: @order.whatsapp_number, placeholder: "e.g. +233123456789", 
              class: "w-full md:w-[50%] rounded-md border border-grey-light outline-none px-3 py-2 mt-2 h-[40px] placeholder:font-thin placeholder:italic" %>
          </div>

          <div class="flex-1 mt-6">
            <label class="block text-base font-semibold">Reference</label>
            <%= form.text_area :reference, value: @order.reference, placeholder: "Reference you want us to use", 
              class: "w-full md:w-[50%] h-[100px] resize-none rounded-md border border-grey-light outline-none px-3 py-2 mt-2 h-[40px] placeholder:font-thin placeholder:italic" %>
          </div>
        </div>

        <div class="text-right">
          <%= form.submit "Review Order",
            id: "submit-btn",
            class: "bg-blue-dark text-white font-bold rounded-lg py-2 px-4 mt-8 cursor-pointer hover:bg-grey-dark hover:text-blue-dark transition"
          %>
        </div>
      <% end %>
    </div>

  </div>
</div>


<script>
  document.addEventListener("turbo:load", function() {
    const amountInput = document.getElementById("temp_amount");
    const convertBtn = document.getElementById("convert-btn");
    const result = document.getElementById("result");
    const hiddenAmountField = document.getElementById("amount");
    const currencyForm = document.getElementById('currencyform');
    const submitButton = document.getElementById('submit-btn');
    var exchangeRate = <%= @exchange_rate %>;

    // Display converted amount
    convertBtn.addEventListener("click", function() {
      const selectedCurrency = document.querySelector('input[name="currency"]:checked').value;
      const amount = parseFloat(amountInput.value);
    
      if (isNaN(amount)) {
        result.textContent = "Invalid amount.";
        return;
      }

      let convertedAmount;
      
      if (selectedCurrency === "cedi") {
        convertedAmount = (amount * exchangeRate).toFixed(2);
        result.textContent = `¥ ${convertedAmount}`;
      } else if (selectedCurrency === "rmb") {
        convertedAmount = (amount / exchangeRate).toFixed(2);
        result.textContent = `₵ ${convertedAmount}`;
      }
    });

    //Update amount field
    submitButton.addEventListener("click", function() {
      const selectedCurrency = document.querySelector('input[name="currency"]:checked').value;
      const amount = parseFloat(amountInput.value);
    
      if (isNaN(amount)) {
        result.textContent = "0";
        return;
      }

      let convertedAmount;
      if (selectedCurrency === "cedi") {
        hiddenAmountField.value = amount.toFixed(2); //Set amount
      } else if (selectedCurrency === "rmb") {
        hiddenAmountField.value = (amount / exchangeRate).toFixed(2); //Set amount
      }
    })
    
    currencyForm.addEventListener('change', function(event) {
      if (event.target.name === 'currency') {
        const convertButton = document.getElementById('convert-btn');
        convertButton.textContent = event.target.value === 'cedi' ? "Convert to RMB" : "Convert to Cedis";
      }
    });
  });
</script>

app/views/orders/show.html.erb
<div class="w-full p-2 bg-blue-light">
  <%= render 'header' %>

  <div class="bg-white rounded my-4 px-2 ">

    <div class="py-4 border-b-2 m-2 border-grey-light lg:w-[50%] flex justify-between items-center">
      <div class="flex gap-x-4 items-center">
        <div class="w-[80px] h-[80px] rounded-full bg-blue bg-opacity-10 text-blue flex justify-center items-center">
          <%= @order.user.username_initials %>
        </div>
        <div>
          <div class="text-lg"><%= @order.user.nil? ? "Guest User" : @order.user&.username %></div>
          <div class="text-grey-dark text-xs">GHS <%= format_amount(@order.amount) %></div>
          <div class="text-xs <%= order_status_color(@order.status) %>"><%= @order.status %></div>
        </div>
      </div>
      <div>
        <% if @order.status == "Pending" %>
          <%= form_with(model: @order, url: order_path(@order), method: :patch) do |form| %>
            <div>
              <%= form.select :status,
                options_for_select(Order.status_options, @order.status),
                {},
                class: "rounded border-blue",
                onchange: "this.form.submit()"
              %>
            </div>
          <% end %>
        <% else %>
          <div class="<%=order_status_bg_dark(@order.status)%> text-white font-semibold rounded p-2 px-4">
            <%= @order.status %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="text-grey-dark font-medium mt-4">
      <div class="mb-4">
        <div>Date</div>
        <div class="w-[80%] md:w-[60%] lg:w-[40%] px-4 py-2 border border-grey-light"> <%= format_date(@order.created_at) %> </div>
      </div>
      <div class="mb-4">
        <div>Reference</div>
        <div class="w-[80%] md:w-[60%] lg:w-[40%] px-4 py-2 border border-grey-light"> <%= @order.reference %> </div>
      </div>
      <div class="mb-4">
        <div>Rate</div>
        <div class="w-[80%] md:w-[60%] lg:w-[40%] px-4 py-2 border border-grey-light"> <%= format_amount(@order.rate) %> </div>
      </div>
      <div class="mb-4">
        <div>Account name</div>
        <div class="w-[80%] md:w-[60%] lg:w-[40%] px-4 py-2 border border-slate_medium text-font_grey"> 
          <%= @order.recipient_account.account_name %>
        </div>
      </div>
      <div class="mb-4">
        <div>Account number</div>
        <div class="w-[80%] md:w-[60%] lg:w-[40%] px-4 py-2 border border-slate_medium text-font_grey"> 
          <%= @order.recipient_account.account_number %>
        </div>
      </div>
      <% if @order.recipient_account.qr_code_url %>
        <div class="mb-4">
          <div>QR code</div>
          <div class="w-[80%] md:w-[60%] lg:w-[40%] px-4 py-2 border border-slate_medium text-font_grey">
            <img src="<%= @order.recipient_account.qr_code_url %>"/>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/summary.html.erb
<div class="bg-blue-light p-8 h-screen">
  <div class="bg-white md:w-[70%] mx-auto rounded-xl p-4 shadow">
    <!-- Order summary -->
    <div class="flex">
      <div class="bg-white px-2 text-bold rounded-lg w-fit h-fit border-4 border-grey-light hover:shadow-md transition-shadow">
        <%= link_to new_order_path(@order) do %>
          <i class="bi-arrow-left text-2xl"></i>
        <% end %>
      </div>
    </div>
    <div>
      <div class="text-2xl text-blue-dark text-center">Order summary</div>
      <table class="bg-grey-light bg-opacity-30 mt-4 mb-8 w-[70%] border border-grey-dark rounded mx-auto">
        <tbody>
          <tr>
            <td class="p-2">Order details</td>
            <td></td>
          </tr>
          <tr class="bg-white">
            <td class="p-2">Order amount (Cedis)</td>
            <td><%= format_amount(@order.amount)%></td>
          </tr>
          <tr class="bg-white">
            <td class="p-2">Order amount (RMB)</td>
            <td><%= format_amount(convert_to_rmb(@order.amount, @exchange_rate))%></td>
          </tr>
          <tr>
            <td class="p-2">Account type</td>
            <td><%= @order.recipient_account.account_type.name %> </td>
          </tr>
          <tr class="bg-white">
            <td class="p-2">Account details</td>
            <td><%= @order.recipient_account.account_name %> &nbsp; - &nbsp; <%= @order.recipient_account.account_number%></td>
          </tr>
          <tr>
            <td class="p-2">Payment method</td>
            <td><%= @order.payer_account.account_type.name%></td>
          </tr>
          <tr class="bg-white">
            <td class="p-2">Paying account</td>
            <td><%= @order.payer_account.account_name %> &nbsp; - &nbsp; <%= @order.payer_account.account_number%></td>
          </tr>
        </tbody>
      </table>
      <div class="w-[70%] mx-auto flex justify-end">
        <%= form_with url: confirm_orders_path, method: :post do %>
          <%= submit_tag "Confirm Order", class: "bg-blue text-white font-semibold px-4 py-2 rounded-md mt-2 cursor-pointer" %>
        <% end %>
      </div>
    </div>
  </div>
</div>